apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: hello-world
        image: registry.gitlab.piyushkashyap.com:5005/root/hello-world:latest
        ports:
        - containerPort: 5000
